// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type Asset = string
export type Name = string
export type Uint64 = number | string

export interface Balances extends BalancesBase {
}

export interface BalancesBase {
  id: Uint64
  contract: Name
  quantity: Asset
}

export interface Counts extends CountsBase {
}

export interface CountsBase {
  key: Name
  secondary_key: Name
  value: Uint64
}

export interface Newid {
  coop_id: Uint64
}

