// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type IAsset = string
export type IName = string
export type ISymbol = string

export interface IAccount {
  balance: IAsset
}

export interface IClose {
  owner: IName
  symbol: ISymbol
}

export interface ICreate {
  issuer: IName
  maximum_supply: IAsset
}

export interface ICurrencyStats {
  supply: IAsset
  max_supply: IAsset
  issuer: IName
}

export interface IIssue {
  to: IName
  quantity: IAsset
  memo: string
}

export interface IOpen {
  owner: IName
  symbol: ISymbol
  ram_payer: IName
}

export interface IRetire {
  quantity: IAsset
  memo: string
}

export interface ITransfer {
  from: IName
  to: IName
  quantity: IAsset
  memo: string
}

