// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type Asset = string
export type Name = string
export type TimePointSec = string
export type Uint64 = number | string

export interface Balances extends BalancesBase {
}

export interface BalancesBase {
  id: Uint64
  contract: Name
  quantity: Asset
}

export interface Counts extends CountsBase {
}

export interface CountsBase {
  key: Name
  secondary_key: Name
  value: Uint64
}

export interface Deposit {
  coopname: Name
  username: Name
  type: Name
  quantity: Asset
}

export interface Deposits {
  id: Uint64
  username: Name
  coopname: Name
  type: Name
  token_contract: Name
  quantity: Asset
  status: Name
  link: string
  memo: string
  expired_at: TimePointSec
}

export interface Document {
  hash: string
  pkey: string
  sign: string
  meta: string
}

export interface Dpcomplete {
  coopname: Name
  admin: Name
  deposit_id: Uint64
  memo: string
}

export interface Dpfail {
  coopname: Name
  admin: Name
  deposit_id: Uint64
  memo: string
}

export interface Newdepositid {
  username: Name
  id: Uint64
}

export interface Newwithdrid {
  username: Name
  id: Uint64
}

export interface Withdraw {
  coopname: Name
  username: Name
  quantity: Asset
  document: Document
  bank_data_id: string
  memo: string
}

export interface Withdrawauth {
  coopname: Name
  withdraw_id: Uint64
}

export interface Withdraws {
  id: Uint64
  username: Name
  coopname: Name
  bank_data_id: string
  token_contract: Name
  quantity: Asset
  status: Name
  document: Document
  memo: string
  created_at: TimePointSec
}

export interface Wthdcomplete {
  coopname: Name
  admin: Name
  withdraw_id: Uint64
  memo: string
}

export interface Wthdfail {
  coopname: Name
  admin: Name
  withdraw_id: Uint64
  memo: string
}

