// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type Asset = string
export type Name = string
export type TimePointSec = string
export type Uint64 = number | string

export interface Accept {
  coopname: Name
  username: Name
  exchange_id: Uint64
  document: Document
}

export interface Addpieces {
  coopname: Name
  username: Name
  exchange_id: Uint64
  new_pieces: Uint64
}

export interface Authorize {
  coopname: Name
  exchange_id: Uint64
  contribution_product_decision_id: Uint64
  contribution_product_authorization: Document
  return_product_decision_id: Uint64
  return_product_authorization: Document
}

export interface Cancel {
  coopname: Name
  username: Name
  exchange_id: Uint64
}

export interface Complete {
  coopname: Name
  username: Name
  exchange_id: Uint64
}

export interface Decline {
  coopname: Name
  username: Name
  exchange_id: Uint64
  meta: string
}

export interface Delivered {
  coopname: Name
  username: Name
  exchange_id: Uint64
}

export interface Dispute {
  coopname: Name
  username: Name
  exchange_id: Uint64
  document: Document
}

export interface Document {
  hash: string
  pkey: string
  sign: string
  meta: string
}

export interface Exchange {
  id: Uint64
  parent_id: Uint64
  program_id: Uint64
  coopname: Name
  type: Name
  status: Name
  username: Name
  parent_username: Name
  token_contract: Name
  unit_cost: Asset
  supplier_amount: Asset
  total_cost: Asset
  membership_fee: Asset
  remain_units: Uint64
  blocked_units: Uint64
  delivered_units: Uint64
  data: string
  meta: string
  money_contributor: Name
  product_contributor: Name
  contribute_product_statement: Document
  return_product_statement: Document
  contribution_product_decision_id: Uint64
  contribution_product_authorization: Document
  return_product_decision_id: Uint64
  return_product_authorization: Document
  product_contribution_act_validation: Document
  product_contribution_act: Document
  product_recieve_act: Document
  product_recieve_act_validation: Document
  product_lifecycle_secs: Uint64
  cancellation_fee: Uint64
  cancellation_fee_amount: Asset
  created_at: TimePointSec
  accepted_at: TimePointSec
  supplied_at: TimePointSec
  delivered_at: TimePointSec
  recieved_at: TimePointSec
  completed_at: TimePointSec
  declined_at: TimePointSec
  disputed_at: TimePointSec
  canceled_at: TimePointSec
  warranty_delay_until: TimePointSec
  deadline_for_receipt: TimePointSec
  is_warranty_return: boolean
  warranty_return_id: Uint64
}

export interface ExchangeParams {
  username: Name
  parent_id: Uint64
  program_id: Uint64
  coopname: Name
  pieces: Uint64
  unit_cost: Asset
  product_lifecycle_secs: Uint64
  document: Document
  data: string
  meta: string
}

export interface Moderate {
  coopname: Name
  username: Name
  exchange_id: Uint64
  cancellation_fee: Uint64
}

export interface Newid {
  id: Uint64
  type: Name
}

export interface Offer {
  params: ExchangeParams
}

export interface Order {
  params: ExchangeParams
}

export interface Prohibit {
  coopname: Name
  username: Name
  exchange_id: Uint64
  meta: string
}

export interface Publish {
  coopname: Name
  username: Name
  exchange_id: Uint64
}

export interface Recieve {
  coopname: Name
  username: Name
  exchange_id: Uint64
  document: Document
}

export interface Recievecnfrm {
  coopname: Name
  username: Name
  exchange_id: Uint64
  document: Document
}

export interface Supply {
  coopname: Name
  username: Name
  exchange_id: Uint64
  document: Document
}

export interface Supplycnfrm {
  coopname: Name
  username: Name
  exchange_id: Uint64
  document: Document
}

export interface Unpublish {
  coopname: Name
  username: Name
  exchange_id: Uint64
}

export interface Update {
  coopname: Name
  username: Name
  exchange_id: Uint64
  remain_units: Uint64
  unit_cost: Asset
  data: string
  meta: string
}

