// Generated by eosio-abi2ts 1.2.2 - eosio::abi/1.2

export type Asset = string
export type Name = string
export type TimePointSec = string
export type Uint64 = number | string

export interface Act {
  coopname: Name
  username: Name
  action: Name
  decision_id: Uint64
  document: Document
}

export interface Addbalance {
  coopname: Name
  username: Name
  quantity: Asset
}

export interface Addprogbal {
  coopname: Name
  username: Name
  program_id: Uint64
  quantity: Asset
}

export interface Address {
  latitude: string
  longitude: string
  country: string
  state: string
  city: string
  district: string
  street: string
  house_number: string
  building_section: string
  unit_number: string
  directions: string
  phone_number: string
  business_hours: string
}

export interface Addresses {
  id: Uint64
  coopname: Name
  cooplate: Name
  data: Address
  meta: string
}

export interface Addstaff {
  coopname: Name
  chairman: Name
  username: Name
  rights: Right[]
  position_title: string
}

export interface Authorize {
  coopname: Name
  chairman: Name
  decision_id: Uint64
  document: Document
}

export interface Automate {
  coopname: Name
  board_id: Uint64
  member: Name
  action_type: Name
  provider: Name
  encrypted_private_key: string
}

export interface Automator {
  id: Uint64
  coopname: Name
  board_id: Uint64
  member: Name
  action_type: Name
  permission_name: Name
  encrypted_private_key: string
}

export interface Autosigner {
  decision_id: Uint64
}

export interface Batch {
  coopname: Name
  action: Name
  batch_id: Uint64
}

export interface Blockbal {
  coopname: Name
  username: Name
  quantity: Asset
}

export interface BoardMember {
  username: Name
  is_voting: boolean
  position_title: string
  position: Name
}

export interface Boards {
  id: Uint64
  type: Name
  name: string
  description: string
  members: BoardMember[]
  created_at: TimePointSec
  last_update: TimePointSec
}

export interface Cancelorder {
  coopname: Name
  username: Name
  exchange_id: Uint64
}

export interface Cancelvote {
  coopname: Name
  member: Name
  decision_id: Uint64
}

export interface Change {
  coopname: Name
  parent_username: Name
  username: Name
  exchange_id: Uint64
  money_contributor: Name
  product_contributor: Name
}

export interface Changes {
  id: Uint64
  exchange_id: Uint64
  contribution_product_decision_id: Uint64
  return_product_decision_id: Uint64
}

export interface Completed {
  coopname: Name
  exchange_id: Uint64
}

export interface Counts extends CountsBase {
}

export interface CountsBase {
  key: Name
  secondary_key: Name
  value: Uint64
}

export interface Creaddress {
  coopname: Name
  chairman: Name
  cooplate: Name
  data: Address
  meta: string
}

export interface Createboard {
  coopname: Name
  chairman: Name
  type: Name
  members: BoardMember[]
  name: string
  description: string
}

export interface Createprog {
  coopname: Name
  chairman: Name
  title: string
  announce: string
  description: string
  preview: string
  images: string
  calculation_type: Name
  fixed_membership_contribution: Asset
  membership_percent_fee: Uint64
}

export interface Decision {
  coopname: Name
  username: Name
  action: Name
  decision_id: Uint64
  document: Document
}

export interface Decisions {
  id: Uint64
  coopname: Name
  username: Name
  type: Name
  batch_id: Uint64
  votes_for: Name[]
  votes_against: Name[]
  validated: boolean
  approved: boolean
  authorized: boolean
  authorization: Document
  created_at: TimePointSec
}

export interface Deladdress {
  coopname: Name
  chairman: Name
  address_id: Uint64
}

export interface Disableprog {
  coopname: Name
  id: Uint64
}

export interface Disautomate {
  coopname: Name
  board_id: Uint64
  member: Name
  automation_id: Uint64
}

export interface Document {
  hash: string
  pkey: string
  sign: string
  meta: string
}

export interface Draft {
  coopname: Name
  username: Name
  decision_id: Uint64
}

export interface Editaddress {
  coopname: Name
  chairman: Name
  address_id: Uint64
  cooplate: Name
  data: Address
  meta: string
}

export interface Editprog {
  coopname: Name
  id: Uint64
  title: string
  announce: string
  description: string
  preview: string
  images: string
}

export interface Exec {
  executer: Name
  coopname: Name
  decision_id: Uint64
}

export interface Fundwithdraw {
  coopname: Name
  username: Name
  type: Name
  withdraw_id: Uint64
  document: Document
}

export interface Joincoop {
  coopname: Name
  username: Name
  document: Document
}

export interface Joincoops {
  id: Uint64
  username: Name
  is_paid: boolean
  statement: Document
  notice: string
}

export interface Mcontribute {
  coopname: Name
  username: Name
  program_id: Uint64
  type: Name
  secondary_id: Uint64
}

export interface Participants {
  username: Name
  created_at: TimePointSec
  last_update: TimePointSec
  last_min_pay: TimePointSec
  status: Name
  is_initial: boolean
  is_minimum: boolean
  has_vote: boolean
}

export interface Pcontribute {
  coopname: Name
  username: Name
  program_id: Uint64
  type: Name
  secondary_id: Uint64
}

export interface Progcomarket {
  id: Uint64
  coopname: Name
  is_active: boolean
  title: string
  announce: string
  description: string
  preview: string
  images: string
  meta: string
  calculation_type: Name
  membership_percent_fee: Uint64
  fixed_membership_contribution: Asset
}

export interface Program {
  coopname: Name
  program_id: Uint64
}

export interface Progwallets {
  id: Uint64
  coopname: Name
  program_id: Uint64
  username: Name
  available: Asset
}

export interface Recieved {
  coopname: Name
  exchange_id: Uint64
}

export interface Regpaid {
  coopname: Name
  username: Name
}

export interface Right {
  contract: Name
  action_name: Name
}

export interface Rmstaff {
  coopname: Name
  chairman: Name
  username: Name
}

export interface Setrights {
  coopname: Name
  chairman: Name
  username: Name
  rights: Right[]
}

export interface Staff {
  username: Name
  position_title: string
  roles: Name[]
  rights: Right[]
  created_at: TimePointSec
  updated_at: TimePointSec
}

export interface Statement {
  coopname: Name
  username: Name
  action: Name
  decision_id: Uint64
  document: Document
}

export interface Subbalance {
  coopname: Name
  username: Name
  quantity: Asset
}

export interface Subprogbal {
  coopname: Name
  username: Name
  program_id: Uint64
  quantity: Asset
}

export interface Unblockbal {
  coopname: Name
  username: Name
  quantity: Asset
}

export interface Updateboard {
  coopname: Name
  chairman: Name
  board_id: Uint64
  members: BoardMember[]
  name: string
  description: string
}

export interface Validate {
  coopname: Name
  username: Name
  decision_id: Uint64
}

export interface Voteagainst {
  coopname: Name
  member: Name
  decision_id: Uint64
}

export interface Votefor {
  coopname: Name
  member: Name
  decision_id: Uint64
}

export interface Wallets {
  username: Name
  available: Asset
  blocked: Asset
  minimum: Asset
}

export interface Withdraw {
  coopname: Name
  username: Name
  withdraw_id: Uint64
}

